apiVersion: v1
items:
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      description: Provides RWO and RWOP Filesystem & Block volumes
    creationTimestamp: "2024-09-30T17:59:39Z"
    labels:
      owned-by.topolvm.io/group: lvm.topolvm.io
      owned-by.topolvm.io/kind: LVMCluster
      owned-by.topolvm.io/name: lvmcluster-sample
      owned-by.topolvm.io/namespace: openshift-storage
      owned-by.topolvm.io/uid: 07553a89-0d80-442b-b03d-336ff8e1b528
      owned-by.topolvm.io/version: v1alpha1
    name: lvms-vg1
    resourceVersion: "21836"
    uid: c628e713-9533-4c51-937e-5ef5b228ca43
  parameters:
    csi.storage.k8s.io/fstype: xfs
    topolvm.io/device-class: vg1
  provisioner: topolvm.io
  reclaimPolicy: Delete
  volumeBindingMode: immediate
kind: List
metadata:
  resourceVersion: ""
